#!/usr/bin/env node

/**
 * Generate runtime-config.js for frontend deployment
 * 
 * This script creates a configuration file that allows the static frontend
 * to connect to a separate backend server. The configuration is generated
 * from environment variables.
 * 
 * Environment Variables:
 * - PUBLIC_API_URL: Base URL for REST API (e.g., https://api.example.com)
 * - PUBLIC_SOCKET_URL: Base URL for Socket.IO (e.g., https://api.example.com)
 * 
 * If environment variables are not set, sensible defaults will be used
 * that work for same-origin deployment.
 */

const fs = require('fs');
const path = require('path');

// Read environment variables
const apiBaseUrl = process.env.PUBLIC_API_URL || '';
const socketUrl = process.env.PUBLIC_SOCKET_URL || '';

// Create configuration object
const config = {
  apiBaseUrl: apiBaseUrl || 'window.location.origin',
  socketUrl: socketUrl || 'window.location.origin'
};

// Generate JavaScript content
const configContent = `// Auto-generated runtime configuration
// This file is generated by scripts/generate-config.js
// DO NOT EDIT THIS FILE MANUALLY

window.APP_CONFIG = ${JSON.stringify(config, null, 2)};

console.log('[Runtime Config] Configuration loaded:', window.APP_CONFIG);
`;

// Ensure public directory exists
const publicDir = path.join(__dirname, '../public');
if (!fs.existsSync(publicDir)) {
  console.error('Error: public directory not found');
  process.exit(1);
}

// Write configuration file
const outputPath = path.join(publicDir, 'runtime-config.js');

try {
  fs.writeFileSync(outputPath, configContent, 'utf8');
  console.log('✅ Runtime configuration generated successfully');
  console.log(`   Output: ${outputPath}`);
  console.log(`   API Base URL: ${apiBaseUrl || '(same-origin)'}`);
  console.log(`   Socket URL: ${socketUrl || '(same-origin)'}`);
} catch (error) {
  console.error('❌ Failed to generate runtime configuration:', error.message);
  process.exit(1);
}
